name = "Boltzmannomics"
version = "0.1.0"
license = "GNU General Public License v3.0"
author = "Ian Friedrichs"
maintainer = "ianfriedri@outlook.com"
copyright = "Copyright 2025, Ian Friedrichs"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
# Might not be needed actually 
#   https://github.com/fortran-lang/fpm/issues/773
#   https://fortran-lang.discourse.group/t/fpm-issue-with-preprocessor-defined-use-statements/8371/7
external-modules = ["mpi"]

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
